---
model:
  d_model: 128
  num_heads: 4
  mha_type: selective
  rope: true
  num_layers: 6

dataset:
  seq_len: 300

trainer:
  batch_size: 16
  n_training_iter: 200000
  n_eval_iter: 20

mode: online

hydra:
  job:
    chdir: true
